name: HelloWorld
version: 1.0
author: Jerry
main: me.Jerry.HelloWorld.Main
description: Our first minecraft spigot plugin!

commands:
   hello:
    aliases: [hi]
    description: This is the hello command
    usage: /hello
    